language: perl
install: cpanm --notest Test::Whitespaces DBI DBD::mysql Test::Deep Test::Most

before_script:
  - mysql -e 'create database sql_easy;'

script: prove -v -l t xt

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
